
ALTER TABLE COMPLICACIONES_MEDICAS ADD(
   CONSTRAINT COM_CK_TCM CHECK (TIPO_COMPLICACION IN ('E','R')) /*E:ENFERMEDAD, R:REVISION*/
);

ALTER TABLE PERSONAS ADD(
   CONSTRAINT PER_CK_TPE CHECK (TIPO_PERSONA IN ('T','C','V')) /*T:TRABAJADOR, C:COMPRADOR, V:VETERINARIO*/
);

ALTER TABLE LOCACIONES ADD(
   CONSTRAINT LOC_FK_IDMU FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIOS(ID_MUNICIPIO)
);


ALTER TABLE FINCAS ADD(
   CONSTRAINT FIN_FK_IDLO FOREIGN KEY (ID_LOCACION) REFERENCES LOCACIONES(ID_LOCACION),
   CONSTRAINT FIN_FK_IDTR FOREIGN KEY (ID_TRABAJADOR) REFERENCES PERSONAS(ID_PERSONA)
);

ALTER TABLE VENTAS ADD(
   CONSTRAINT VEN_FK_IDCO FOREIGN KEY (ID_COMPRADOR) REFERENCES PERSONAS(ID_PERSONA)
);

ALTER TABLE RESES ADD(
   CONSTRAINT RES_FK_IDER FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIES_RES(ID_ESPECIE),
   CONSTRAINT RES_FK_IDFI FOREIGN KEY (ID_FINCA) REFERENCES FINCAS(ID_FINCA),
   CONSTRAINT RES_FK_IDRE FOREIGN KEY (ID_REGISTRO) REFERENCES REGISTROS(ID_REGISTRO),
   CONSTRAINT RES_FK_IDVE FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA),
   CONSTRAINT RES_CK_TGE CHECK (GENERO IN ('M','F')) /*M:MASCULINO, F:FEMENINO*/
);

ALTER TABLE HISTORIAL_CLINICO ADD( 
   CONSTRAINT HICL_FK_IDCM FOREIGN KEY (ID_COMPLICACION_MEDICA) REFERENCES COMPLICACIONES_MEDICAS(ID_COMPLICACION_MEDICA),
   CONSTRAINT HICL_FK_IDRE FOREIGN KEY (ID_RES) REFERENCES RESES(ID_RES),
   CONSTRAINT HICL_FK_IDVE FOREIGN KEY (ID_VETERINARIO) REFERENCES PERSONAS(ID_PERSONA)
);