
CREATE TABLE MUNICIPIOS (
   ID_MUNICIPIO         NUMBER(11)     NOT NULL,
   NOMBRE_MUNICIPIO     VARCHAR2(30)   NOT NULL,
   CONSTRAINT MUN_PK_IDMU PRIMARY KEY (ID_MUNICIPIO)
);


CREATE TABLE ESPECIES_RES (
   ID_ESPECIE        NUMBER(11)     NOT NULL,
   NOMBRE_ESPECIE    VARCHAR2(30)   NOT NULL,
   CONSTRAINT ESRE_PK_IDER PRIMARY KEY (ID_ESPECIE)
);


CREATE TABLE COMPLICACIONES_MEDICAS (
   ID_COMPLICACION_MEDICA     NUMBER(11)     NOT NULL,
   NOMBRE_COMPLICACION        VARCHAR2(30)   NOT NULL,
   TIPO_COMPLICACION          CHAR(1)        NOT NULL,
   DESCRIPCION                VARCHAR2(30)           ,
   CONSTRAINT COME_PK_IDCM PRIMARY KEY (ID_COMPLICACION_MEDICA)
);


CREATE TABLE REGISTROS (
   ID_REGISTRO       NUMBER(11)     NOT NULL,
   FECHA_LLEGADA     DATE           NOT NULL,
   CONSTRAINT REG_PK_IDRE PRIMARY KEY (ID_REGISTRO)
);


CREATE TABLE PERSONAS (
   ID_PERSONA           NUMBER(11)        NOT NULL,
   NOMBRE_PERSONA       VARCHAR2(30)              ,
   APELLIDO_PERSONA     VARCHAR2(30)      NOT NULL,
   TELEFONO_PERSONA     VARCHAR2(30)      NOT NULL,
   TIPO_PERSONA         CHAR(1)           NOT NULL,
   SALARIO              NUMBER(8,2)               ,
   CONSTRAINT PER_PK_IDPE PRIMARY KEY (ID_PERSONA)
);


CREATE TABLE LOCACIONES (
   ID_LOCACION    NUMBER(11)     NOT NULL,
   ID_MUNICIPIO   NUMBER(11)     NOT NULL,
   DIRECCION      VARCHAR2(30)   NOT NULL,
   CONSTRAINT LOC_PK_IDLO PRIMARY KEY (ID_LOCACION)
);


CREATE TABLE FINCAS (
   ID_FINCA          NUMBER(11)     NOT NULL,
   ID_LOCACION       NUMBER(11)     NOT NULL,
   ID_TRABAJADOR     NUMBER(11)     NOT NULL,
   NOMBRE_FINCA      VARCHAR2(30)   NOT NULL,
   CONSTRAINT FIN_PK_IDFI PRIMARY KEY (ID_FINCA)
);

CREATE TABLE VENTAS (
   ID_VENTA       NUMBER(11)     NOT NULL,
   ID_COMPRADOR   NUMBER(11)     NOT NULL,
   VALOR_VENTA    NUMBER(8)      NOT NULL,
   FECHA          DATE           NOT NULL,
   CONSTRAINT VEN_PK_IDVE PRIMARY KEY (ID_VENTA)
);


CREATE TABLE RESES (
   ID_RES               NUMBER(11)     NOT NULL,
   NOMBRE_RES           VARCHAR(30)             ,
   GENERO               CHAR(1)        NOT NULL,
   COLOR                VARCHAR2(30)   NOT NULL,
   FECHA_NACIMINETO     DATE           NOT NULL,
   ID_REGISTRO          NUMBER(11)     NOT NULL,
   ID_ESPECIE           NUMBER(11)     NOT NULL,
   ID_VENTA             NUMBER(11)             ,
   ID_FINCA             NUMBER(11)     NOT NULL,
   CONSTRAINT RES_PK_IDRS PRIMARY KEY (ID_RES)
);


CREATE TABLE HISTORIAL_CLINICO (
   ID_VETERINARIO          NUMBER(11)     NOT NULL,
   ID_RES                  NUMBER(11)     NOT NULL,
   ID_COMPLICACION_MEDICA  NUMBER(11)     NOT NULL,
   COSTO_REVISION          NUMBER(5)      NOT NULL,
   FECHA_REVISION          DATE           NOT NULL,
   FECHA_MUERTE            DATE                   ,
   CONSTRAINT HICL_PK_IDPRS PRIMARY KEY (ID_VETERINARIO, ID_RES, ID_COMPLICACION_MEDICA)
);